### ISSUE TITLE
Next Brisbane NodeSchool date / location / details discussion

### ISSUE THREAD

**Issue by garrows** [nodeschool/brisbane#1]
Welcome to Brisbane's nodeschool discussion group :) Let's try to get a nodeschool day happening here before the end of the year. Thanks @pajarraco for getting us started. 
## Dates

There isn't any direction in regards to the Sydney or Melbourne groups. I'm not available until Mid November (but that doesn't mean you can't start without me). 

Here are the Sydney & Melbourne main date discussions if we want to try to sync up with them however it's not necessary.
https://github.com/nodeschool/sydney/issues/1
https://github.com/nodeschool/melbourne/issues/1
## Venue

The main 2 locations I can think of are the Edge or the Hackerspace. Anyone else got suggestions?
## People

Some people who have volunteered or suggested to possibly help on the day are:
@pyrotechnick @MauriceButler @AnnaGerber @korynunn @MattMS 
@rvagg said that he might fly up for it depending on timing.

**Comment by KoryNunn** [comment]
I'd be happy to help out. Agree with it being after CampJS.

**Comment by garrows** [comment]
Thanks for the BrisJs offer @kevdesign in https://github.com/nodeschool/organizers/issues/19#issuecomment-56477004

**Comment by pajarraco** [comment]
Hi, I am going to CampJS and i like to meet us there, how can i find you?

**Comment by garrows** [comment]
That's great. I'm the one with the big ginger beard.
